spring.datasource.url=jdbc:postgresql://postgres:5432/stockpilot
spring.datasource.username=stockpilot
spring.datasource.password=stockpilot123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.port=8080
